### PR TITLE
[Fix] typo & spellcheck

### PR DESCRIPTION
**Pull request by SebastienElet**
Fixes #

### Proposed changes
- Spellcheck on considerations_for_generating_api_clients.html
- Spellcheck on webservices_at_7digital.html

### Code quality
- I was unable to run the dev target

### Join
- [x] I wish to join the core team
- [x] I agree that with great powers comes responsibilities
- [ ] I'm a nice person

My NPM username: sebastienelet

### CODE REVIEW

**Comment by nfroidure** [comment]
Thanks! Can you paste the result of the dev command here?

**Comment by SebastienElet** [comment]
```
❯ npm run dev

> insertafter@0.1.0 dev /Users/sebastien/Dev/blog
> gulp

[10:34:44] Using gulpfile ~/Dev/blog/gulpfile.js
[10:34:44] Starting 'server'...
[10:34:44] Starting 'clean'...
[10:34:44] Finished 'clean' after 2.86 ms
[10:34:44] Starting 'build_fonts'...
[10:34:44] Starting 'build_images'...
[10:34:44] Finished 'build_images' after 221 ms
[10:34:44] Starting 'build_styles'...
[10:34:44] Starting 'build_html'...
[10:34:44] Dev server listening on 33222
[10:34:44] Finished 'server' after 677 ms

events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: convert: unable to open image '/dev/stdout': Permission denied @ error/blob.c/OpenBlob/2919.
convert: WriteBlob Failed `/dev/stdout' @ error/png.c/MagickPNGErrorHandler/1674.

    at Socket.<anonymous> (/Users/sebastien/Dev/blog/node_modules/gulp-spawn/index.js:53:26)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by nfroidure** [comment]
Pretty strange you cannot write to `/dev/stdout`, i thought of a Mac issue but it was working even on Mac for me.

**Comment by SebastienElet** [comment]
Maybe it's a sign to adopt docker for your blog 😄

**Pull request merged**
